### ISSUE TITLE
[Feature] Animations per item

### ISSUE THREAD

**Issue by Havoclivekiller** [wrycu/StarWarsFFG-Enhancements#31]
Allow an override to the animations per item. There are some weapons like grenades or different types of melee weapons that would benefit from a different animation (or none at all).

I think you could either add another tab in the item sheet or have these settings under the Configuration tab.

**Comment by wrycu** [comment]
I'm working on implementing this.

**Comment by wrycu** [comment]
I've got it working, but have a bit of work left to do to clean things up. Here's how it looks:

![image](https://user-images.githubusercontent.com/4709746/119242683-d7d91400-bb14-11eb-8a28-1a16cc09fb26.png)

![image](https://user-images.githubusercontent.com/4709746/119242685-df98b880-bb14-11eb-907d-d1c23cdb05f2.png)

It's not entirely ideal since you can't set it from the item sheet itself, but I couldn't find a clean way to do it without a ton of work.

**Comment by Havoclivekiller** [comment]
Sure. Let's hope it will work without issues. Good job.

**Comment by wrycu** [comment]
Done. Will be released in `0.1.8`.
