### ISSUE TITLE
Module somehow enables Star Wars FFG System to use StarJedi font, system uses it wrong

### ISSUE THREAD

**Issue by Sherbniz** [wrycu/StarWarsFFG-Enhancements#37]
![d](https://user-images.githubusercontent.com/13256855/119244031-9d02ca80-bb6c-11eb-8f8a-fd0e6349bbb8.png)

After enabling this addon, suddendly the "Mandar" style of the Star Wars FFG System will be able to use the StarJedi font, and incorrect use of the font causes some strange text-artifacts where letters are switched.

[https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/900](url)

Changing the mandar.css of the system like in the above issue fixes the problem.

Although I am still not sure why this addon triggered this. Perhaps worth a look.

**Comment by wrycu** [comment]
As discussed on Discord, this isn't actually an issue with this module - rather, we provide the font that the `Mandar` theme was trying to use and the artifacting is a result of the way in which the theme is trying to use it.  

That being said, since our module exposes it, I'll override the CSS applied by the theme until the next system update comes out and fixes it, at which point I'll stop overriding it.

**Comment by wrycu** [comment]
Will be released in `0.1.8`.
