### ISSUE TITLE
Compatibility with 1.5

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#49]
Confirm all functionality works with FVTT `0.7.10` and FFG SW `1.5`.

Creating as a result of #48

- [x] Settings
- [x] Intro Crawl
- [x] Datapad creator
- [x] Bounty creator
- [x] Shop
- [x] Attack animations
- [x] Talent checker
- [x] Combat renamer
- [x] Dice helper
- [x] Strain remainder

**Comment by wrycu** [comment]
The vendor default size appears to be too small for the shop content:
![image](https://user-images.githubusercontent.com/4709746/121236357-b719f980-c84a-11eb-9ba0-2bc9967c8326.png)

**Comment by wrycu** [comment]
Looks like there are no breaking changes. Easier than expected. :)

**Comment by BrenniusXIV** [comment]
Hi there! I'm looking to try out your module on FVTT v.0.7.10, FFG v. 1.5; however, one of the modules which is a dependency of yours ([foundryvtt-fxmaster](https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster)) throws an error requiring a core FVTT update to 0.8.6 to function. Naturally, since FFG isn't compatible with 0.8.6 yet, this makes installing your module more difficult. I'm able to install your module by installing fxmaster v1.0.4. Is there something in the installation instructions that I have missed to avoid having to downgrade to this version? Are there other solutions for this problem?

Thanks in advance for your time, and my apologies if this problem has been addressed already or if I have posted this in the wrong section :)

**Comment by wrycu** [comment]
I'll write up a guide on installation steps in the wiki to try and make this less painful - beyond that, there isn't much that can be done - I can't pin specific versions of modules as dependencies and I'm not super happy about the idea of investing a lot of time into working around that limitation when support for `0.8.x` should be forthcoming in the near future.

Thank you for the comment and it's no trouble at all. Feel free to DM me on Discord if you have more thoughts on the matter.
